Update .travis.yml

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -32,13 +32,13 @@ addons:
       - g++-multilib
 
 before_install:
-  - echo "Build directory: $TRAVIS_BUILD_DIR"
-  - echo "Build number: $TRAVIS_BUILD_NUMBER"
-  - echo "Branch: $TRAVIS_BRANCH"
-  - echo "Tag: $TRAVIS_TAG"
-  - echo "Commit: $TRAVIS_COMMIT"
+  - echo "Build directory: "$TRAVIS_BUILD_DIR
+  - echo "Build number: "$TRAVIS_BUILD_NUMBER
+  - echo "Branch: "$TRAVIS_BRANCH
+  - echo "Tag: "$TRAVIS_TAG
+  - echo "Commit: "$TRAVIS_COMMIT
   - COMMIT_TIMESTAMP=`git log -1 --pretty=format:%ci | sed -r 's/(.*) (.*) (.*)/\1T\2\3/'`
-  - echo "Commit timestamp: $COMMIT_TIMESTAMP"
+  - echo "Commit timestamp: "$COMMIT_TIMESTAMP
   - git --version
   - git config --global user.name "Travis CI"
   - git config --global user.email "travis@travis-ci.org"
@@ -68,12 +68,23 @@ script:
   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run electron-builder:linux-x64; fi
 
 after_success:
-  - if [[ "$TRAVIS_NODE_VERSION" != "4" ]]; then exit 0; fi
-  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bash -c 'cd output; zip -q -r cncjs-darwin-x64.zip cncjs-darwin-x64/'; fi
-  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bash -c 'scripts/travis-release-darwin-x64.sh output/cncjs-darwin-x64.zip'; fi
-  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash -c 'cd output; zip -q -r cncjs-linux-x64.zip cncjs-linux-x64/'; fi
-  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash -c 'scripts/travis-release-linux-x64.sh output/cncjs-linux-x64.zip'; fi
-  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash -c 'scripts/travis-docker-build.sh'; fi
+  # This makes the script exit with a non-zero error code if any of the commands fails.
+  - set -e
+  - if [[ "$TRAVIS_NODE_VERSION" == "4" && "$TRAVIS_OS_NAME" == "osx" ]]; then
+      pushd output;
+      zip -q -r cncjs-darwin-x64.zip cncjs-darwin-x64/;
+      popd;
+      scripts/travis-release-darwin-x64.sh output/cncjs-darwin-x64.zip;
+    fi
+  - if [[ "$TRAVIS_NODE_VERSION" == "4" && "$TRAVIS_OS_NAME" == "linux" ]]; then
+      pushd output;
+      zip -q -r cncjs-linux-x64.zip cncjs-linux-x64/;
+      popd;
+      scripts/travis-release-linux-x64.sh output/cncjs-linux-x64.zip;
+    fi
+  - if [[ "$TRAVIS_NODE_VERSION" == "5" && "$TRAVIS_OS_NAME" == "linux" ]]; then
+      scripts/travis-docker-build.sh;
+    fi
 
 before_deploy:
   - export DEPLOY_FILE=$(ls output/cncjs-*.zip)
